apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-soknad-pdf
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{ kafka_pool }}
  replicas:
    min: 3
    max: 3
  resources:
    limits:
      cpu: 12
      memory: 2024Mi
    requests:
      cpu: 350m
      memory: 1024Mi
  secureLogs:
    enabled: true
  env:
    - name: DP_MELLOMLAGRING_SCOPE
      value: {{ DP_MELLOMLAGRING_SCOPE }}
    - name: DP_SOKNAD_SCOPE
      value: {{ DP_SOKNAD_SCOPE }}
    - name: PDL_API_HOST
      value: {{ PDL_API_HOST }}
    - name: PDL_API_SCOPE
      value: {{ PDL_API_SCOPE }}
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-mellomlagring
        - application: dp-soknad
      external:
        - host: {{PDL_API_HOST}}