apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-soknad-pdf
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: "{{ kafka_pool }}"
  replicas:
    min: 3
    max: 3
  resources:
    limits:
      cpu: "12" # Denne appen KAN bruke mye CPU, så vi bør ha en limit
      memory: 1536Mi
    requests:
      cpu: 100m
      memory: 768Mi
  secureLogs:
    enabled: true
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4
    - name: DP_MELLOMLAGRING_SCOPE
      value: "{{ DP_MELLOMLAGRING_SCOPE }}"
    - name: DP_SOKNAD_SCOPE
      value: "{{ DP_SOKNAD_SCOPE }}"
    - name: PDL_API_HOST
      value: "{{ PDL_API_HOST }}"
    - name: PDL_API_SCOPE
      value: "{{ PDL_API_SCOPE }}"
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-mellomlagring
        - application: dp-soknad
      external:
        - host: "{{PDL_API_HOST}}"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
