apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-behov-soknad-pdf
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: {{ kafka_pool }}
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-mellomlagring
